"use client";
import Head from "next/head";
import {
  Container,
  Main,
} from "@styles/sharedstyles";
import { Header } from "@components/Header";
import { SearchContainer } from "@components/containers/SearchContainer";
import { FileList } from "@components/containers/FileList";
import { FilesContainer } from "@components/containers/FilesContainer";

export default function Home() {
  return (
    <Container>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header/>
      <Main>
        <FilesContainer>
          <SearchContainer/>
          <FileList />
        </FilesContainer>
      </Main>
    </Container>
  );
}
