"use client";
import Head from "next/head";
import {
  Container,
  Main,
} from "./src/components/commons/sharedstyles";
import { Header } from "./src/components/commons/Header";

export default function Home() {
  return (
    <Container>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header/>
      <Main>
      </Main>
    </Container>
  );
}
