"use client";
import Head from "next/head";
import {
  Container,
  Main,
} from "@styles/sharedstyles";
import { Header } from "@components/Header";
import { SearchBar } from "@components/inputs/SearchBar"
import { NewFileButton } from "@components/buttons/NewFileButton";

export default function Home() {
  return (
    <Container>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header/>
      <Main>
        <SearchBar />
        <NewFileButton/>
      </Main>
    </Container>
  );
}
